this.createjs=this.createjs||{};(function(){var c=createjs.SoundJS=createjs.SoundJS||{};c.version="NEXT";c.buildDate="Fri, 04 Dec 2015 17:24:04 GMT"})();this.createjs=this.createjs||{};createjs.extend=function(c,b){function a(){this.constructor=c}a.prototype=b.prototype;return c.prototype=new a};this.createjs=this.createjs||{};
createjs.promote=function(c,b){var a=c.prototype,d=Object.getPrototypeOf&&Object.getPrototypeOf(a)||a.__proto__;if(d){a[(b+="_")+"constructor"]=d.constructor;for(var h in d)a.hasOwnProperty(h)&&"function"==typeof d[h]&&(a[b+h]=d[h])}return c};this.createjs=this.createjs||{};createjs.indexOf=function(c,b){for(var a=0,d=c.length;a<d;a++)if(b===c[a])return a;return-1};this.createjs=this.createjs||{};
(function(){createjs.proxy=function(c,b){var a=Array.prototype.slice.call(arguments,2);return function(){return c.apply(b,Array.prototype.slice.call(arguments,0).concat(a))}}})();this.createjs=this.createjs||{};
(function(){function c(){throw"BrowserDetect cannot be instantiated";}var b=c.agent=window.navigator.userAgent;c.isWindowPhone=-1<b.indexOf("IEMobile")||-1<b.indexOf("Windows Phone");c.isFirefox=-1<b.indexOf("Firefox");c.isOpera=null!=window.opera;c.isChrome=-1<b.indexOf("Chrome");c.isIOS=(-1<b.indexOf("iPod")||-1<b.indexOf("iPhone")||-1<b.indexOf("iPad"))&&!c.isWindowPhone;c.isAndroid=-1<b.indexOf("Android")&&!c.isWindowPhone;c.isBlackberry=-1<b.indexOf("Blackberry");createjs.BrowserDetect=c})();
this.createjs=this.createjs||{};
(function(){function c(){this._captureListeners=this._listeners=null}var b=c.prototype;c.initialize=function(a){a.addEventListener=b.addEventListener;a.on=b.on;a.removeEventListener=a.off=b.removeEventListener;a.removeAllEventListeners=b.removeAllEventListeners;a.hasEventListener=b.hasEventListener;a.dispatchEvent=b.dispatchEvent;a._dispatchEvent=b._dispatchEvent;a.willTrigger=b.willTrigger};b.addEventListener=function(a,d,b){var c;c=b?this._captureListeners=this._captureListeners||{}:this._listeners=
	this._listeners||{};var e=c[a];e&&this.removeEventListener(a,d,b);(e=c[a])?e.push(d):c[a]=[d];return d};b.on=function(a,d,b,c,e,g){d.handleEvent&&(b=b||d,d=d.handleEvent);b=b||this;return this.addEventListener(a,function(a){d.call(b,a,e);c&&a.remove()},g)};b.removeEventListener=function(a,d,b){if(b=b?this._captureListeners:this._listeners){var c=b[a];if(c)for(var e=0,g=c.length;e<g;e++)if(c[e]==d){1==g?delete b[a]:c.splice(e,1);break}}};b.off=b.removeEventListener;b.removeAllEventListeners=function(a){a?
	(this._listeners&&delete this._listeners[a],this._captureListeners&&delete this._captureListeners[a]):this._listeners=this._captureListeners=null};b.dispatchEvent=function(a,d,b){if("string"==typeof a){var c=this._listeners;if(!(d||c&&c[a]))return!0;a=new createjs.Event(a,d,b)}else a.target&&a.clone&&(a=a.clone());try{a.target=this}catch(e){}if(a.bubbles&&this.parent){b=this;for(d=[b];b.parent;)d.push(b=b.parent);c=d.length;for(b=c-1;0<=b&&!a.propagationStopped;b--)d[b]._dispatchEvent(a,1+(0==b));
	for(b=1;b<c&&!a.propagationStopped;b++)d[b]._dispatchEvent(a,3)}else this._dispatchEvent(a,2);return!a.defaultPrevented};b.hasEventListener=function(a){var d=this._listeners,b=this._captureListeners;return!!(d&&d[a]||b&&b[a])};b.willTrigger=function(a){for(var d=this;d;){if(d.hasEventListener(a))return!0;d=d.parent}return!1};b.toString=function(){return"[EventDispatcher]"};b._dispatchEvent=function(a,d){var b,c=1==d?this._captureListeners:this._listeners;if(a&&c&&(c=c[a.type])&&(b=c.length)){try{a.currentTarget=
	this}catch(k){}try{a.eventPhase=d}catch(k){}a.removed=!1;for(var c=c.slice(),e=0;e<b&&!a.immediatePropagationStopped;e++){var g=c[e];g.handleEvent?g.handleEvent(a):g(a);a.removed&&(this.off(a.type,g,1==d),a.removed=!1)}}};createjs.EventDispatcher=c})();this.createjs=this.createjs||{};
(function(){function c(a,d,b){this.type=a;this.currentTarget=this.target=null;this.eventPhase=0;this.bubbles=!!d;this.cancelable=!!b;this.timeStamp=(new Date).getTime();this.removed=this.immediatePropagationStopped=this.propagationStopped=this.defaultPrevented=!1}var b=c.prototype;b.preventDefault=function(){this.defaultPrevented=this.cancelable&&!0};b.stopPropagation=function(){this.propagationStopped=!0};b.stopImmediatePropagation=function(){this.immediatePropagationStopped=this.propagationStopped=
	!0};b.remove=function(){this.removed=!0};b.clone=function(){return new c(this.type,this.bubbles,this.cancelable)};b.set=function(a){for(var d in a)this[d]=a[d];return this};b.toString=function(){return"[Event (type="+this.type+")]"};createjs.Event=c})();this.createjs=this.createjs||{};
(function(){function c(b,a,d){this.Event_constructor("error");this.title=b;this.message=a;this.data=d}createjs.extend(c,createjs.Event).clone=function(){return new createjs.ErrorEvent(this.title,this.message,this.data)};createjs.ErrorEvent=createjs.promote(c,"Event")})();this.createjs=this.createjs||{};
(function(c){function b(a,d){this.Event_constructor("progress");this.loaded=a;this.total=null==d?1:d;this.progress=0==d?0:this.loaded/this.total}createjs.extend(b,createjs.Event).clone=function(){return new createjs.ProgressEvent(this.loaded,this.total)};createjs.ProgressEvent=createjs.promote(b,"Event")})(window);this.createjs=this.createjs||{};
(function(){function c(){this.id=this.type=this.src=null;this.maintainOrder=!1;this.data=this.callback=null;this.method=createjs.LoadItem.GET;this.headers=this.values=null;this.withCredentials=!1;this.crossOrigin=this.mimeType=null;this.loadTimeout=a.LOAD_TIMEOUT_DEFAULT}var b=c.prototype={},a=c;a.LOAD_TIMEOUT_DEFAULT=8E3;a.create=function(d){if("string"==typeof d){var b=new c;b.src=d;return b}if(d instanceof a)return d;if(d instanceof Object&&d.src)return null==d.loadTimeout&&(d.loadTimeout=a.LOAD_TIMEOUT_DEFAULT),
	d;throw Error("Type not recognized.");};b.set=function(a){for(var b in a)this[b]=a[b];return this};createjs.LoadItem=a})();
(function(){var c={ABSOLUTE_PATT:/^(?:\w+:)?\/{2}/i,RELATIVE_PATT:/^[./]*?\//i,EXTENSION_PATT:/\/?[^/]+\.(\w{1,5})$/i,parseURI:function(b){var a={absolute:!1,relative:!1};if(null==b)return a;var d=b.indexOf("?");-1<d&&(b=b.substr(0,d));c.ABSOLUTE_PATT.test(b)?a.absolute=!0:c.RELATIVE_PATT.test(b)&&(a.relative=!0);if(b=b.match(c.EXTENSION_PATT))a.extension=b[1].toLowerCase();return a},formatQueryString:function(b,a){if(null==b)throw Error("You must specify data.");var d=[],c;for(c in b)d.push(c+"="+
escape(b[c]));a&&(d=d.concat(a));return d.join("&")},buildPath:function(b,a){if(null==a)return b;var d=[],c=b.indexOf("?");if(-1!=c)var f=b.slice(c+1),d=d.concat(f.split("&"));return-1!=c?b.slice(0,c)+"?"+this.formatQueryString(a,d):b+"?"+this.formatQueryString(a,d)},isCrossDomain:function(b){var a=document.createElement("a");a.href=b.src;b=document.createElement("a");b.href=location.href;return""!=a.hostname&&(a.port!=b.port||a.protocol!=b.protocol||a.hostname!=b.hostname)},isLocal:function(b){var a=
	document.createElement("a");a.href=b.src;return""==a.hostname&&"file:"==a.protocol},isBinary:function(b){switch(b){case createjs.AbstractLoader.IMAGE:case createjs.AbstractLoader.BINARY:return!0;default:return!1}},isImageTag:function(b){return b instanceof HTMLImageElement},isAudioTag:function(b){return window.HTMLAudioElement?b instanceof HTMLAudioElement:!1},isVideoTag:function(b){return window.HTMLVideoElement?b instanceof HTMLVideoElement:!1},isText:function(b){switch(b){case createjs.AbstractLoader.TEXT:case createjs.AbstractLoader.JSON:case createjs.AbstractLoader.MANIFEST:case createjs.AbstractLoader.XML:case createjs.AbstractLoader.CSS:case createjs.AbstractLoader.SVG:case createjs.AbstractLoader.JAVASCRIPT:case createjs.AbstractLoader.SPRITESHEET:return!0;
	default:return!1}},getTypeByExtension:function(b){if(null==b)return createjs.AbstractLoader.TEXT;switch(b.toLowerCase()){case "jpeg":case "jpg":case "gif":case "png":case "webp":case "bmp":return createjs.AbstractLoader.IMAGE;case "ogg":case "mp3":case "webm":return createjs.AbstractLoader.SOUND;case "mp4":case "webm":case "ts":return createjs.AbstractLoader.VIDEO;case "json":return createjs.AbstractLoader.JSON;case "xml":return createjs.AbstractLoader.XML;case "css":return createjs.AbstractLoader.CSS;
	case "js":return createjs.AbstractLoader.JAVASCRIPT;case "svg":return createjs.AbstractLoader.SVG;default:return createjs.AbstractLoader.TEXT}}};createjs.RequestUtils=c})();this.createjs=this.createjs||{};
(function(){function c(a,d,b){this.EventDispatcher_constructor();this.canceled=this.loaded=!1;this.progress=0;this.type=b;this.resultFormatter=null;this._item=a?createjs.LoadItem.create(a):null;this._preferXHR=d;this._tag=this._tagSrcAttribute=this._loadedItems=this._rawResult=this._result=null}var b=createjs.extend(c,createjs.EventDispatcher);c.POST="POST";c.GET="GET";c.BINARY="binary";c.CSS="css";c.IMAGE="image";c.JAVASCRIPT="javascript";c.JSON="json";c.JSONP="jsonp";c.MANIFEST="manifest";c.SOUND=
	"sound";c.VIDEO="video";c.SPRITESHEET="spritesheet";c.SVG="svg";c.TEXT="text";c.XML="xml";b.getItem=function(){return this._item};b.getResult=function(a){return a?this._rawResult:this._result};b.getTag=function(){return this._tag};b.setTag=function(a){this._tag=a};b.load=function(){this._createRequest();this._request.on("complete",this,this);this._request.on("progress",this,this);this._request.on("loadStart",this,this);this._request.on("abort",this,this);this._request.on("timeout",this,this);this._request.on("error",
	this,this);var a=new createjs.Event("initialize");a.loader=this._request;this.dispatchEvent(a);this._request.load()};b.cancel=function(){this.canceled=!0;this.destroy()};b.destroy=function(){this._request&&(this._request.removeAllEventListeners(),this._request.destroy());this._loadItems=this._result=this._rawResult=this._item=this._request=null;this.removeAllEventListeners()};b.getLoadedItems=function(){return this._loadedItems};b._createRequest=function(){this._request=this._preferXHR?new createjs.XHRRequest(this._item):
	new createjs.TagRequest(this._item,this._tag||this._createTag(),this._tagSrcAttribute)};b._createTag=function(a){return null};b._sendLoadStart=function(){this._isCanceled()||this.dispatchEvent("loadstart")};b._sendProgress=function(a){if(!this._isCanceled()){var d=null;if("number"==typeof a)this.progress=a,d=new createjs.ProgressEvent(this.progress);else if(d=a,this.progress=a.loaded/a.total,d.progress=this.progress,isNaN(this.progress)||Infinity==this.progress)this.progress=0;this.hasEventListener("progress")&&
this.dispatchEvent(d)}};b._sendComplete=function(){if(!this._isCanceled()){this.loaded=!0;var a=new createjs.Event("complete");a.rawResult=this._rawResult;null!=this._result&&(a.result=this._result);this.dispatchEvent(a)}};b._sendError=function(a){!this._isCanceled()&&this.hasEventListener("error")&&(null==a&&(a=new createjs.ErrorEvent("PRELOAD_ERROR_EMPTY")),this.dispatchEvent(a))};b._isCanceled=function(){return null==window.createjs||this.canceled?!0:!1};b.resultFormatter=null;b.handleEvent=function(a){switch(a.type){case "complete":this._rawResult=
	a.target._response;a=this.resultFormatter&&this.resultFormatter(this);a instanceof Function?a.call(this,createjs.proxy(this._resultFormatSuccess,this),createjs.proxy(this._resultFormatFailed,this)):(this._result=a||this._rawResult,this._sendComplete());break;case "progress":this._sendProgress(a);break;case "error":this._sendError(a);break;case "loadstart":this._sendLoadStart();break;case "abort":case "timeout":this._isCanceled()||this.dispatchEvent(new createjs.ErrorEvent("PRELOAD_"+a.type.toUpperCase()+
"_ERROR"))}};b._resultFormatSuccess=function(a){this._result=a;this._sendComplete()};b._resultFormatFailed=function(a){this._sendError(a)};b.buildPath=function(a,d){return createjs.RequestUtils.buildPath(a,d)};b.toString=function(){return"[PreloadJS AbstractLoader]"};createjs.AbstractLoader=createjs.promote(c,"EventDispatcher")})();this.createjs=this.createjs||{};
(function(){function c(a,d,b){this.AbstractLoader_constructor(a,d,b);this.resultFormatter=this._formatResult;this._tagSrcAttribute="src";this.on("initialize",this._updateXHR,this)}var b=createjs.extend(c,createjs.AbstractLoader);b.load=function(){this._tag||(this._tag=this._createTag(this._item.src));this._tag.preload="auto";this._tag.load();this.AbstractLoader_load()};b._createTag=function(){};b._createRequest=function(){this._request=this._preferXHR?new createjs.XHRRequest(this._item):new createjs.MediaTagRequest(this._item,
	this._tag||this._createTag(),this._tagSrcAttribute)};b._updateXHR=function(a){a.loader.setResponseType&&a.loader.setResponseType("blob")};b._formatResult=function(a){this._tag.removeEventListener&&this._tag.removeEventListener("canplaythrough",this._loadedHandler);this._tag.onstalled=null;if(this._preferXHR){var d=window.URL||window.webkitURL,b=a.getResult(!0);a.getTag().src=d.createObjectURL(b)}return a.getTag()};createjs.AbstractMediaLoader=createjs.promote(c,"AbstractLoader")})();
this.createjs=this.createjs||{};(function(){var c=function(a){this._item=a},b=createjs.extend(c,createjs.EventDispatcher);b.load=function(){};b.destroy=function(){};b.cancel=function(){};createjs.AbstractRequest=createjs.promote(c,"EventDispatcher")})();this.createjs=this.createjs||{};
(function(){function c(a,d,b){this.AbstractRequest_constructor(a);this._tag=d;this._tagSrcAttribute=b;this._loadedHandler=createjs.proxy(this._handleTagComplete,this);this._addedToDOM=!1;this._startTagVisibility=null}var b=createjs.extend(c,createjs.AbstractRequest);b.load=function(){this._tag.onload=createjs.proxy(this._handleTagComplete,this);this._tag.onreadystatechange=createjs.proxy(this._handleReadyStateChange,this);this._tag.onerror=createjs.proxy(this._handleError,this);var a=new createjs.Event("initialize");
	a.loader=this._tag;this.dispatchEvent(a);this._hideTag();this._loadTimeout=setTimeout(createjs.proxy(this._handleTimeout,this),this._item.loadTimeout);this._tag[this._tagSrcAttribute]=this._item.src;null==this._tag.parentNode&&(window.document.body.appendChild(this._tag),this._addedToDOM=!0)};b.destroy=function(){this._clean();this._tag=null;this.AbstractRequest_destroy()};b._handleReadyStateChange=function(){clearTimeout(this._loadTimeout);var a=this._tag;"loaded"!=a.readyState&&"complete"!=a.readyState||
this._handleTagComplete()};b._handleError=function(){this._clean();this.dispatchEvent("error")};b._handleTagComplete=function(){this._rawResult=this._tag;this._result=this.resultFormatter&&this.resultFormatter(this)||this._rawResult;this._clean();this._showTag();this.dispatchEvent("complete")};b._handleTimeout=function(){this._clean();this.dispatchEvent(new createjs.Event("timeout"))};b._clean=function(){this._tag.onload=null;this._tag.onreadystatechange=null;this._tag.onerror=null;this._addedToDOM&&
null!=this._tag.parentNode&&this._tag.parentNode.removeChild(this._tag);clearTimeout(this._loadTimeout)};b._hideTag=function(){this._startTagVisibility=this._tag.style.visibility;this._tag.style.visibility="hidden"};b._showTag=function(){this._tag.style.visibility=this._startTagVisibility};b._handleStalled=function(){};createjs.TagRequest=createjs.promote(c,"AbstractRequest")})();this.createjs=this.createjs||{};
(function(){function c(a,d,b){this.AbstractRequest_constructor(a);this._tag=d;this._tagSrcAttribute=b;this._loadedHandler=createjs.proxy(this._handleTagComplete,this)}var b=createjs.extend(c,createjs.TagRequest);b.load=function(){var a=createjs.proxy(this._handleStalled,this);this._stalledCallback=a;var d=createjs.proxy(this._handleProgress,this);this._handleProgress=d;this._tag.addEventListener("stalled",a);this._tag.addEventListener("progress",d);this._tag.addEventListener&&this._tag.addEventListener("canplaythrough",
	this._loadedHandler,!1);this.TagRequest_load()};b._handleReadyStateChange=function(){clearTimeout(this._loadTimeout);var a=this._tag;"loaded"!=a.readyState&&"complete"!=a.readyState||this._handleTagComplete()};b._handleStalled=function(){};b._handleProgress=function(a){!a||0<a.loaded&&0==a.total||(a=new createjs.ProgressEvent(a.loaded,a.total),this.dispatchEvent(a))};b._clean=function(){this._tag.removeEventListener&&this._tag.removeEventListener("canplaythrough",this._loadedHandler);this._tag.removeEventListener("stalled",
	this._stalledCallback);this._tag.removeEventListener("progress",this._progressCallback);this.TagRequest__clean()};createjs.MediaTagRequest=createjs.promote(c,"TagRequest")})();this.createjs=this.createjs||{};
(function(){function c(a){this.AbstractRequest_constructor(a);this._loadTimeout=this._request=null;this._xhrLevel=1;this._rawResponse=this._response=null;this._canceled=!1;this._handleLoadStartProxy=createjs.proxy(this._handleLoadStart,this);this._handleProgressProxy=createjs.proxy(this._handleProgress,this);this._handleAbortProxy=createjs.proxy(this._handleAbort,this);this._handleErrorProxy=createjs.proxy(this._handleError,this);this._handleTimeoutProxy=createjs.proxy(this._handleTimeout,this);this._handleLoadProxy=
	createjs.proxy(this._handleLoad,this);this._handleReadyStateChangeProxy=createjs.proxy(this._handleReadyStateChange,this);this._createXHR(a)}var b=createjs.extend(c,createjs.AbstractRequest);c.ACTIVEX_VERSIONS="Msxml2.XMLHTTP.6.0 Msxml2.XMLHTTP.5.0 Msxml2.XMLHTTP.4.0 MSXML2.XMLHTTP.3.0 MSXML2.XMLHTTP Microsoft.XMLHTTP".split(" ");b.getResult=function(a){return a&&this._rawResponse?this._rawResponse:this._response};b.cancel=function(){this.canceled=!0;this._clean();this._request.abort()};b.load=function(){if(null==
	this._request)this._handleError();else{null!=this._request.addEventListener?(this._request.addEventListener("loadstart",this._handleLoadStartProxy,!1),this._request.addEventListener("progress",this._handleProgressProxy,!1),this._request.addEventListener("abort",this._handleAbortProxy,!1),this._request.addEventListener("error",this._handleErrorProxy,!1),this._request.addEventListener("timeout",this._handleTimeoutProxy,!1),this._request.addEventListener("load",this._handleLoadProxy,!1),this._request.addEventListener("readystatechange",
	this._handleReadyStateChangeProxy,!1)):(this._request.onloadstart=this._handleLoadStartProxy,this._request.onprogress=this._handleProgressProxy,this._request.onabort=this._handleAbortProxy,this._request.onerror=this._handleErrorProxy,this._request.ontimeout=this._handleTimeoutProxy,this._request.onload=this._handleLoadProxy,this._request.onreadystatechange=this._handleReadyStateChangeProxy);1==this._xhrLevel&&(this._loadTimeout=setTimeout(createjs.proxy(this._handleTimeout,this),this._item.loadTimeout));
	try{this._item.values&&this._item.method!=createjs.AbstractLoader.GET?this._item.method==createjs.AbstractLoader.POST&&this._request.send(createjs.RequestUtils.formatQueryString(this._item.values)):this._request.send()}catch(a){this.dispatchEvent(new createjs.ErrorEvent("XHR_SEND",null,a))}}};b.setResponseType=function(a){"blob"===a&&(this._responseType=a=window.URL?"blob":"arraybuffer");this._request.responseType=a};b.getAllResponseHeaders=function(){return this._request.getAllResponseHeaders instanceof
Function?this._request.getAllResponseHeaders():null};b.getResponseHeader=function(a){return this._request.getResponseHeader instanceof Function?this._request.getResponseHeader(a):null};b._handleProgress=function(a){!a||0<a.loaded&&0==a.total||(a=new createjs.ProgressEvent(a.loaded,a.total),this.dispatchEvent(a))};b._handleLoadStart=function(a){clearTimeout(this._loadTimeout);this.dispatchEvent("loadstart")};b._handleAbort=function(a){this._clean();this.dispatchEvent(new createjs.ErrorEvent("XHR_ABORTED",
	null,a))};b._handleError=function(a){this._clean();this.dispatchEvent(new createjs.ErrorEvent(a.message))};b._handleReadyStateChange=function(a){4==this._request.readyState&&this._handleLoad()};b._handleLoad=function(a){if(!this.loaded)if(this.loaded=!0,a=this._checkError())this._handleError(a);else{this._response=this._getResponse();if("arraybuffer"===this._responseType)try{this._response=new Blob([this._response])}catch(d){window.BlobBuilder=window.BlobBuilder||window.WebKitBlobBuilder||window.MozBlobBuilder||
window.MSBlobBuilder,"TypeError"===d.name&&window.BlobBuilder&&(a=new BlobBuilder,a.append(this._response),this._response=a.getBlob())}this._clean();this.dispatchEvent(new createjs.Event("complete"))}};b._handleTimeout=function(a){this._clean();this.dispatchEvent(new createjs.ErrorEvent("PRELOAD_TIMEOUT",null,a))};b._checkError=function(){var a=parseInt(this._request.status);switch(a){case 404:case 0:return Error(a)}return null};b._getResponse=function(){if(null!=this._response)return this._response;
	if(null!=this._request.response)return this._request.response;try{if(null!=this._request.responseText)return this._request.responseText}catch(a){}try{if(null!=this._request.responseXML)return this._request.responseXML}catch(a){}return null};b._createXHR=function(a){var d=createjs.RequestUtils.isCrossDomain(a),b={},c=null;if(window.XMLHttpRequest)c=new XMLHttpRequest,d&&void 0===c.withCredentials&&window.XDomainRequest&&(c=new XDomainRequest);else{for(var e=0,g=s.ACTIVEX_VERSIONS.length;e<g;e++){var k=
	s.ACTIVEX_VERSIONS[e];try{c=new ActiveXObject(k);break}catch(m){}}if(null==c)return!1}null==a.mimeType&&createjs.RequestUtils.isText(a.type)&&(a.mimeType="text/plain; charset=utf-8");a.mimeType&&c.overrideMimeType&&c.overrideMimeType(a.mimeType);this._xhrLevel="string"===typeof c.responseType?2:1;e=null;e=a.method==createjs.AbstractLoader.GET?createjs.RequestUtils.buildPath(a.src,a.values):a.src;c.open(a.method||createjs.AbstractLoader.GET,e,!0);d&&c instanceof XMLHttpRequest&&1==this._xhrLevel&&
(b.Origin=location.origin);a.values&&a.method==createjs.AbstractLoader.POST&&(b["Content-Type"]="application/x-www-form-urlencoded");d||b["X-Requested-With"]||(b["X-Requested-With"]="XMLHttpRequest");if(a.headers)for(var l in a.headers)b[l]=a.headers[l];for(l in b)c.setRequestHeader(l,b[l]);c instanceof XMLHttpRequest&&void 0!==a.withCredentials&&(c.withCredentials=a.withCredentials);this._request=c;return!0};b._clean=function(){clearTimeout(this._loadTimeout);null!=this._request.removeEventListener?
	(this._request.removeEventListener("loadstart",this._handleLoadStartProxy),this._request.removeEventListener("progress",this._handleProgressProxy),this._request.removeEventListener("abort",this._handleAbortProxy),this._request.removeEventListener("error",this._handleErrorProxy),this._request.removeEventListener("timeout",this._handleTimeoutProxy),this._request.removeEventListener("load",this._handleLoadProxy),this._request.removeEventListener("readystatechange",this._handleReadyStateChangeProxy)):
	(this._request.onloadstart=null,this._request.onprogress=null,this._request.onabort=null,this._request.onerror=null,this._request.ontimeout=null,this._request.onload=null,this._request.onreadystatechange=null)};b.toString=function(){return"[PreloadJS XHRRequest]"};createjs.XHRRequest=createjs.promote(c,"AbstractRequest")})();this.createjs=this.createjs||{};
(function(){function c(a,d){this.AbstractMediaLoader_constructor(a,d,createjs.AbstractLoader.SOUND);createjs.RequestUtils.isAudioTag(a)?this._tag=a:createjs.RequestUtils.isAudioTag(a.src)?this._tag=a:createjs.RequestUtils.isAudioTag(a.tag)&&(this._tag=createjs.RequestUtils.isAudioTag(a)?a:a.src);null!=this._tag&&(this._preferXHR=!1)}var b=createjs.extend(c,createjs.AbstractMediaLoader);c.canLoadItem=function(a){return a.type==createjs.AbstractLoader.SOUND};b._createTag=function(a){var d=document.createElement("audio");
	d.autoplay=!1;d.preload="none";d.src=a;return d};createjs.SoundLoader=createjs.promote(c,"AbstractMediaLoader")})();this.createjs=this.createjs||{};
(function(){var c=function(){this.duration=this.startTime=this.pan=this.volume=this.loop=this.offset=this.delay=this.interrupt=null},b=c.prototype={};c.create=function(a){if(a instanceof c||a instanceof Object){var d=new createjs.PlayPropsConfig;d.set(a);return d}throw Error("Type not recognized.");};b.set=function(a){for(var d in a)this[d]=a[d];return this};b.toString=function(){return"[PlayPropsConfig]"};createjs.PlayPropsConfig=c})();this.createjs=this.createjs||{};
(function(){function c(){throw"Sound cannot be instantiated";}function b(a,b){this.init(a,b)}c.INTERRUPT_ANY="any";c.INTERRUPT_EARLY="early";c.INTERRUPT_LATE="late";c.INTERRUPT_NONE="none";c.PLAY_INITED="playInited";c.PLAY_SUCCEEDED="playSucceeded";c.PLAY_INTERRUPTED="playInterrupted";c.PLAY_FINISHED="playFinished";c.PLAY_FAILED="playFailed";c.SUPPORTED_EXTENSIONS="mp3 ogg opus mpeg wav m4a mp4 aiff wma mid".split(" ");c.EXTENSION_MAP={m4a:"mp4"};c.FILE_PATTERN=/^(?:(\w+:)\/{2}(\w+(?:\.\w+)*\/?))?([/.]*?(?:[^?]+)?\/)?((?:[^/?]+)\.(\w+))(?:\?(\S+)?)?$/;
	c.defaultInterruptBehavior=c.INTERRUPT_NONE;c.alternateExtensions=[];c.activePlugin=null;c._masterVolume=1;Object.defineProperty(c,"volume",{get:function(){return this._masterVolume},set:function(a){if(null==Number(a))return!1;a=Math.max(0,Math.min(1,a));c._masterVolume=a;if(!this.activePlugin||!this.activePlugin.setVolume||!this.activePlugin.setVolume(a))for(var b=this._instances,f=0,e=b.length;f<e;f++)b[f].setMasterVolume(a)}});c._masterMute=!1;Object.defineProperty(c,"muted",{get:function(){return this._masterMute},
		set:function(a){if(null==a)return!1;this._masterMute=a;if(!this.activePlugin||!this.activePlugin.setMute||!this.activePlugin.setMute(a))for(var b=this._instances,c=0,e=b.length;c<e;c++)b[c].setMasterMute(a);return!0}});Object.defineProperty(c,"capabilities",{get:function(){return null==c.activePlugin?null:c.activePlugin._capabilities},set:function(a){return!1}});c._pluginsRegistered=!1;c._lastID=0;c._instances=[];c._idHash={};c._preloadHash={};c._defaultPlayPropsHash={};c.addEventListener=null;c.removeEventListener=
		null;c.removeAllEventListeners=null;c.dispatchEvent=null;c.hasEventListener=null;c._listeners=null;createjs.EventDispatcher.initialize(c);c.getPreloadHandlers=function(){return{callback:createjs.proxy(c.initLoad,c),types:["sound"],extensions:c.SUPPORTED_EXTENSIONS}};c._handleLoadComplete=function(a){var b=a.target.getItem().src;if(c._preloadHash[b])for(var f=0,e=c._preloadHash[b].length;f<e;f++){var g=c._preloadHash[b][f];c._preloadHash[b][f]=!0;c.hasEventListener("fileload")&&(a=new createjs.Event("fileload"),
		a.src=g.src,a.id=g.id,a.data=g.data,a.sprite=g.sprite,c.dispatchEvent(a))}};c._handleLoadError=function(a){var b=a.target.getItem().src;if(c._preloadHash[b])for(var f=0,e=c._preloadHash[b].length;f<e;f++){var g=c._preloadHash[b][f];c._preloadHash[b][f]=!1;c.hasEventListener("fileerror")&&(a=new createjs.Event("fileerror"),a.src=g.src,a.id=g.id,a.data=g.data,a.sprite=g.sprite,c.dispatchEvent(a))}};c._registerPlugin=function(a){return a.isSupported()?(c.activePlugin=new a,!0):!1};c.registerPlugins=
		function(a){c._pluginsRegistered=!0;for(var b=0,f=a.length;b<f;b++)if(c._registerPlugin(a[b]))return!0;return!1};c.initializeDefaultPlugins=function(){return null!=c.activePlugin?!0:c._pluginsRegistered?!1:c.registerPlugins([createjs.WebAudioPlugin,createjs.HTMLAudioPlugin])?!0:!1};c.isReady=function(){return null!=c.activePlugin};c.getCapabilities=function(){return null==c.activePlugin?null:c.activePlugin._capabilities};c.getCapability=function(a){return null==c.activePlugin?null:c.activePlugin._capabilities[a]};
	c.initLoad=function(a){return c._registerSound(a)};c._registerSound=function(a){if(!c.initializeDefaultPlugins())return!1;var h;a.src instanceof Object?(h=c._parseSrc(a.src),h.src=a.path+h.src):h=c._parsePath(a.src);if(null==h)return!1;a.src=h.src;a.type="sound";h=a.data;var f=null;if(null!=h&&(isNaN(h.channels)?isNaN(h)||(f=parseInt(h)):f=parseInt(h.channels),h.audioSprite))for(var e,g=h.audioSprite.length;g--;)e=h.audioSprite[g],c._idHash[e.id]={src:a.src,startTime:parseInt(e.startTime),duration:parseInt(e.duration)},
	e.defaultPlayProps&&(c._defaultPlayPropsHash[e.id]=createjs.PlayPropsConfig.create(e.defaultPlayProps));null!=a.id&&(c._idHash[a.id]={src:a.src});e=c.activePlugin.register(a);b.create(a.src,f);null!=h&&isNaN(h)?a.data.channels=f||b.maxPerChannel():a.data=f||b.maxPerChannel();e.type&&(a.type=e.type);a.defaultPlayProps&&(c._defaultPlayPropsHash[a.src]=createjs.PlayPropsConfig.create(a.defaultPlayProps));return e};c.registerSound=function(a,b,f,e,g){f={src:a,id:b,data:f,defaultPlayProps:g};a instanceof
	Object&&a.src&&(e=b,f=a);f=createjs.LoadItem.create(f);f.path=e;null==e||f.src instanceof Object||(f.src=e+a);a=c._registerSound(f);if(!a)return!1;c._preloadHash[f.src]||(c._preloadHash[f.src]=[]);c._preloadHash[f.src].push(f);if(1==c._preloadHash[f.src].length)a.on("complete",createjs.proxy(this._handleLoadComplete,this)),a.on("error",createjs.proxy(this._handleLoadError,this)),c.activePlugin.preload(a);else if(1==c._preloadHash[f.src][0])return!0;return f};c.registerSounds=function(a,b){var c=[];
		a.path&&(b=b?b+a.path:a.path,a=a.manifest);for(var e=0,g=a.length;e<g;e++)c[e]=createjs.Sound.registerSound(a[e].src,a[e].id,a[e].data,b,a[e].defaultPlayProps);return c};c.removeSound=function(a,h){if(null==c.activePlugin)return!1;a instanceof Object&&a.src&&(a=a.src);var f;a instanceof Object?f=c._parseSrc(a):(a=c._getSrcById(a).src,f=c._parsePath(a));if(null==f)return!1;a=f.src;null!=h&&(a=h+a);for(var e in c._idHash)c._idHash[e].src==a&&delete c._idHash[e];b.removeSrc(a);delete c._preloadHash[a];
		c.activePlugin.removeSound(a);return!0};c.removeSounds=function(a,b){var c=[];a.path&&(b=b?b+a.path:a.path,a=a.manifest);for(var e=0,g=a.length;e<g;e++)c[e]=createjs.Sound.removeSound(a[e].src,b);return c};c.removeAllSounds=function(){c._idHash={};c._preloadHash={};b.removeAll();c.activePlugin&&c.activePlugin.removeAllSounds()};c.loadComplete=function(a){if(!c.isReady())return!1;var b=c._parsePath(a);a=b?c._getSrcById(b.src).src:c._getSrcById(a).src;return void 0==c._preloadHash[a]?!1:1==c._preloadHash[a][0]};
	c._parsePath=function(a){"string"!=typeof a&&(a=a.toString());var b=a.match(c.FILE_PATTERN);if(null==b)return!1;for(var f=b[4],e=b[5],g=c.capabilities,k=0;!g[e];)if(e=c.alternateExtensions[k++],k>c.alternateExtensions.length)return null;a=a.replace("."+b[5],"."+e);return{name:f,src:a,extension:e}};c._parseSrc=function(a){var b={name:void 0,src:void 0,extension:void 0},f=c.capabilities,e;for(e in a)if(a.hasOwnProperty(e)&&f[e]){b.src=a[e];b.extension=e;break}if(!b.src)return!1;a=b.src.lastIndexOf("/");
		b.name=-1!=a?b.src.slice(a+1):b.src;return b};c.play=function(a,b,f,e,g,k,l,m,n){b=b instanceof Object||b instanceof createjs.PlayPropsConfig?createjs.PlayPropsConfig.create(b):createjs.PlayPropsConfig.create({interrupt:b,delay:f,offset:e,loop:g,volume:k,pan:l,startTime:m,duration:n});a=c.createInstance(a,b.startTime,b.duration);c._playInstance(a,b)||a._playFailed();return a};c.createInstance=function(a,h,f){if(!c.initializeDefaultPlugins())return new createjs.DefaultSoundInstance(a,h,f);var e=c._defaultPlayPropsHash[a];
		a=c._getSrcById(a);var g=c._parsePath(a.src),k=null;null!=g&&null!=g.src?(b.create(g.src),null==h&&(h=a.startTime),k=c.activePlugin.create(g.src,h,f||a.duration),(e=e||c._defaultPlayPropsHash[g.src])&&k.applyPlayProps(e)):k=new createjs.DefaultSoundInstance(a,h,f);k.uniqueId=c._lastID++;return k};c.stop=function(){for(var a=this._instances,b=a.length;b--;)a[b].stop()};c.setVolume=function(a){if(null==Number(a))return!1;a=Math.max(0,Math.min(1,a));c._masterVolume=a;if(!this.activePlugin||!this.activePlugin.setVolume||
		!this.activePlugin.setVolume(a))for(var b=this._instances,f=0,e=b.length;f<e;f++)b[f].setMasterVolume(a)};c.getVolume=function(){return this._masterVolume};c.setMute=function(a){if(null==a)return!1;this._masterMute=a;if(!this.activePlugin||!this.activePlugin.setMute||!this.activePlugin.setMute(a))for(var b=this._instances,c=0,e=b.length;c<e;c++)b[c].setMasterMute(a);return!0};c.getMute=function(){return this._masterMute};c.setDefaultPlayProps=function(a,b){a=c._getSrcById(a);c._defaultPlayPropsHash[c._parsePath(a.src).src]=
		createjs.PlayPropsConfig.create(b)};c.getDefaultPlayProps=function(a){a=c._getSrcById(a);return c._defaultPlayPropsHash[c._parsePath(a.src).src]};c._playInstance=function(a,b){var f=c._defaultPlayPropsHash[a.src]||{};null==b.interrupt&&(b.interrupt=f.interrupt||c.defaultInterruptBehavior);null==b.delay&&(b.delay=f.delay||0);null==b.offset&&(b.offset=a.getPosition());null==b.loop&&(b.loop=a.loop);null==b.volume&&(b.volume=a.volume);null==b.pan&&(b.pan=a.pan);if(0==b.delay){if(!c._beginPlaying(a,b))return!1}else f=
		setTimeout(function(){c._beginPlaying(a,b)},b.delay),a.delayTimeoutId=f;this._instances.push(a);return!0};c._beginPlaying=function(a,c){if(!b.add(a,c.interrupt))return!1;if(!a._beginPlaying(c)){var f=createjs.indexOf(this._instances,a);-1<f&&this._instances.splice(f,1);return!1}return!0};c._getSrcById=function(a){return c._idHash[a]||{src:a}};c._playFinished=function(a){b.remove(a);a=createjs.indexOf(this._instances,a);-1<a&&this._instances.splice(a,1)};createjs.Sound=c;b.channels={};b.create=function(a,
																																																																																																																																   c){return null==b.get(a)?(b.channels[a]=new b(a,c),!0):!1};b.removeSrc=function(a){var c=b.get(a);if(null==c)return!1;c._removeAll();delete b.channels[a];return!0};b.removeAll=function(){for(var a in b.channels)b.channels[a]._removeAll();b.channels={}};b.add=function(a,c){var f=b.get(a.src);return null==f?!1:f._add(a,c)};b.remove=function(a){var c=b.get(a.src);if(null==c)return!1;c._remove(a);return!0};b.maxPerChannel=function(){return a.maxDefault};b.get=function(a){return b.channels[a]};var a=b.prototype;
	a.constructor=b;a.src=null;a.max=null;a.maxDefault=100;a.length=0;a.init=function(a,b){this.src=a;this.max=b||this.maxDefault;-1==this.max&&(this.max=this.maxDefault);this._instances=[]};a._get=function(a){return this._instances[a]};a._add=function(a,b){if(!this._getSlot(b,a))return!1;this._instances.push(a);this.length++;return!0};a._remove=function(a){a=createjs.indexOf(this._instances,a);if(-1==a)return!1;this._instances.splice(a,1);this.length--;return!0};a._removeAll=function(){for(var a=this.length-
		1;0<=a;a--)this._instances[a].stop()};a._getSlot=function(a,b){var f,e;if(a!=c.INTERRUPT_NONE&&(e=this._get(0),null==e))return!0;for(var g=0,k=this.max;g<k;g++){f=this._get(g);if(null==f)return!0;if(f.playState==c.PLAY_FINISHED||f.playState==c.PLAY_INTERRUPTED||f.playState==c.PLAY_FAILED){e=f;break}a!=c.INTERRUPT_NONE&&(a==c.INTERRUPT_EARLY&&f.getPosition()<e.getPosition()||a==c.INTERRUPT_LATE&&f.getPosition()>e.getPosition())&&(e=f)}return null!=e?(e._interrupt(),this._remove(e),!0):!1};a.toString=
		function(){return"[Sound SoundChannel]"}})();this.createjs=this.createjs||{};
(function(){var c=function(a,b,c,f){this.EventDispatcher_constructor();this.src=a;this.uniqueId=-1;this.delayTimeoutId=this.playState=null;this._volume=1;Object.defineProperty(this,"volume",{get:this.getVolume,set:this.setVolume});this._pan=0;Object.defineProperty(this,"pan",{get:this.getPan,set:this.setPan});this._startTime=Math.max(0,b||0);Object.defineProperty(this,"startTime",{get:this.getStartTime,set:this.setStartTime});this._duration=Math.max(0,c||0);Object.defineProperty(this,"duration",{get:this.getDuration,
	set:this.setDuration});this._playbackResource=null;Object.defineProperty(this,"playbackResource",{get:this.getPlaybackResource,set:this.setPlaybackResource});!1!==f&&!0!==f&&this.setPlaybackResource(f);this._position=0;Object.defineProperty(this,"position",{get:this.getPosition,set:this.setPosition});this._loop=0;Object.defineProperty(this,"loop",{get:this.getLoop,set:this.setLoop});this._muted=!1;Object.defineProperty(this,"muted",{get:this.getMuted,set:this.setMuted});this._paused=!1;Object.defineProperty(this,
	"paused",{get:this.getPaused,set:this.setPaused})},b=createjs.extend(c,createjs.EventDispatcher);b.play=function(a,b,c,f,e,g){a=a instanceof Object||a instanceof createjs.PlayPropsConfig?createjs.PlayPropsConfig.create(a):createjs.PlayPropsConfig.create({interrupt:a,delay:b,offset:c,loop:f,volume:e,pan:g});if(this.playState==createjs.Sound.PLAY_SUCCEEDED)this.applyPlayProps(a),this._paused&&this.setPaused(!1);else return this._cleanUp(),createjs.Sound._playInstance(this,a),this};b.stop=function(){this._position=
	0;this._paused=!1;this._handleStop();this._cleanUp();this.playState=createjs.Sound.PLAY_FINISHED;return this};b.destroy=function(){this._cleanUp();this.playbackResource=this.src=null;this.removeAllEventListeners()};b.applyPlayProps=function(a){null!=a.offset&&this.setPosition(a.offset);null!=a.loop&&this.setLoop(a.loop);null!=a.volume&&this.setVolume(a.volume);null!=a.pan&&this.setPan(a.pan);null!=a.startTime&&(this.setStartTime(a.startTime),this.setDuration(a.duration));return this};b.toString=function(){return"[AbstractSoundInstance]"};
	b.getPaused=function(){return this._paused};b.setPaused=function(a){if(!(!0!==a&&!1!==a||this._paused==a||1==a&&this.playState!=createjs.Sound.PLAY_SUCCEEDED))return(this._paused=a)?this._pause():this._resume(),clearTimeout(this.delayTimeoutId),this};b.setVolume=function(a){if(a==this._volume)return this;this._volume=Math.max(0,Math.min(1,a));this._muted||this._updateVolume();return this};b.getVolume=function(){return this._volume};b.setMuted=function(a){if(!0===a||!1===a)return this._muted=a,this._updateVolume(),
		this};b.getMuted=function(){return this._muted};b.setPan=function(a){if(a==this._pan)return this;this._pan=Math.max(-1,Math.min(1,a));this._updatePan();return this};b.getPan=function(){return this._pan};b.getPosition=function(){this._paused||this.playState!=createjs.Sound.PLAY_SUCCEEDED||(this._position=this._calculateCurrentPosition());return this._position};b.setPosition=function(a){this._position=Math.max(0,a);this.playState==createjs.Sound.PLAY_SUCCEEDED&&this._updatePosition();return this};b.getStartTime=
		function(){return this._startTime};b.setStartTime=function(a){if(a==this._startTime)return this;this._startTime=Math.max(0,a||0);this._updateStartTime();return this};b.getDuration=function(){return this._duration};b.setDuration=function(a){if(a==this._duration)return this;this._duration=Math.max(0,a||0);this._updateDuration();return this};b.setPlaybackResource=function(a){this._playbackResource=a;0==this._duration&&this._setDurationFromSource();return this};b.getPlaybackResource=function(){return this._playbackResource};
	b.getLoop=function(){return this._loop};b.setLoop=function(a){null!=this._playbackResource&&(0!=this._loop&&0==a?this._removeLooping(a):0==this._loop&&0!=a&&this._addLooping(a));this._loop=a};b._sendEvent=function(a){a=new createjs.Event(a);this.dispatchEvent(a)};b._cleanUp=function(){clearTimeout(this.delayTimeoutId);this._handleCleanUp();this._paused=!1;createjs.Sound._playFinished(this)};b._interrupt=function(){this._cleanUp();this.playState=createjs.Sound.PLAY_INTERRUPTED;this._sendEvent("interrupted")};
	b._beginPlaying=function(a){this.setPosition(a.offset);this.setLoop(a.loop);this.setVolume(a.volume);this.setPan(a.pan);null!=a.startTime&&(this.setStartTime(a.startTime),this.setDuration(a.duration));if(null!=this._playbackResource&&this._position<this._duration)return this._paused=!1,this._handleSoundReady(),this.playState=createjs.Sound.PLAY_SUCCEEDED,this._sendEvent("succeeded"),!0;this._playFailed();return!1};b._playFailed=function(){this._cleanUp();this.playState=createjs.Sound.PLAY_FAILED;
		this._sendEvent("failed")};b._handleSoundComplete=function(a){this._position=0;0!=this._loop?(this._loop--,this._handleLoop(),this._sendEvent("loop")):(this._cleanUp(),this.playState=createjs.Sound.PLAY_FINISHED,this._sendEvent("complete"))};b._handleSoundReady=function(){};b._updateVolume=function(){};b._updatePan=function(){};b._updateStartTime=function(){};b._updateDuration=function(){};b._setDurationFromSource=function(){};b._calculateCurrentPosition=function(){};b._updatePosition=function(){};
	b._removeLooping=function(a){};b._addLooping=function(a){};b._pause=function(){};b._resume=function(){};b._handleStop=function(){};b._handleCleanUp=function(){};b._handleLoop=function(){};createjs.AbstractSoundInstance=createjs.promote(c,"EventDispatcher");createjs.DefaultSoundInstance=createjs.AbstractSoundInstance})();this.createjs=this.createjs||{};
(function(){var c=function(){this._capabilities=null;this._loaders={};this._audioSources={};this._soundInstances={};this._volume=1},b=c.prototype;c._capabilities=null;c.isSupported=function(){return!0};b.register=function(a){var b=this._loaders[a.src];if(b&&!b.canceled)return this._loaders[a.src];this._audioSources[a.src]=!0;this._soundInstances[a.src]=[];b=new this._loaderClass(a);b.on("complete",this._handlePreloadComplete,this);return this._loaders[a.src]=b};b.preload=function(a){a.on("error",
	this._handlePreloadError,this);a.load()};b.isPreloadStarted=function(a){return null!=this._audioSources[a]};b.isPreloadComplete=function(a){return!(null==this._audioSources[a]||1==this._audioSources[a])};b.removeSound=function(a){if(this._soundInstances[a]){for(var b=this._soundInstances[a].length;b--;)this._soundInstances[a][b].destroy();delete this._soundInstances[a];delete this._audioSources[a];this._loaders[a]&&this._loaders[a].destroy();delete this._loaders[a]}};b.removeAllSounds=function(){for(var a in this._audioSources)this.removeSound(a)};
	b.create=function(a,b,c){this.isPreloadStarted(a)||this.preload(this.register(a));b=new this._soundInstanceClass(a,b,c,this._audioSources[a]);this._soundInstances[a].push(b);return b};b.setVolume=function(a){this._volume=a;this._updateVolume();return!0};b.getVolume=function(){return this._volume};b.setMute=function(a){this._updateVolume();return!0};b.toString=function(){return"[AbstractPlugin]"};b._handlePreloadComplete=function(a){var b=a.target.getItem().src;this._audioSources[b]=a.result;a=0;for(var c=
		this._soundInstances[b].length;a<c;a++)this._soundInstances[b][a].setPlaybackResource(this._audioSources[b])};b._handlePreloadError=function(a){};b._updateVolume=function(){};createjs.AbstractPlugin=c})();this.createjs=this.createjs||{};
(function(){function c(a){this.AbstractLoader_constructor(a,!0,createjs.AbstractLoader.SOUND)}var b=createjs.extend(c,createjs.AbstractLoader);c.context=null;b.toString=function(){return"[WebAudioLoader]"};b._createRequest=function(){this._request=new createjs.XHRRequest(this._item,!1);this._request.setResponseType("arraybuffer")};b._sendComplete=function(a){c.context.decodeAudioData(this._rawResult,createjs.proxy(this._handleAudioDecoded,this),createjs.proxy(this._sendError,this))};b._handleAudioDecoded=
	function(a){this._result=a;this.AbstractLoader__sendComplete()};createjs.WebAudioLoader=createjs.promote(c,"AbstractLoader")})();this.createjs=this.createjs||{};
(function(){function c(b,c,f,e){this.AbstractSoundInstance_constructor(b,c,f,e);this.gainNode=a.context.createGain();this.panNode=a.context.createPanner();this.panNode.panningModel=a._panningModel;this.panNode.connect(this.gainNode);this._updatePan();this._sourceNodeNext=this._soundCompleteTimeout=this.sourceNode=null;this._playbackStartTime=0;this._endedHandler=createjs.proxy(this._handleSoundComplete,this)}var b=createjs.extend(c,createjs.AbstractSoundInstance),a=c;a.context=null;a._scratchBuffer=
	null;a.destinationNode=null;a._panningModel="equalpower";b.destroy=function(){this.AbstractSoundInstance_destroy();this.panNode.disconnect(0);this.panNode=null;this.gainNode.disconnect(0);this.gainNode=null};b.toString=function(){return"[WebAudioSoundInstance]"};b._updatePan=function(){this.panNode.setPosition(this._pan,0,-.5)};b._removeLooping=function(a){this._sourceNodeNext=this._cleanUpAudioNode(this._sourceNodeNext)};b._addLooping=function(a){this.playState==createjs.Sound.PLAY_SUCCEEDED&&(this._sourceNodeNext=
	this._createAndPlayAudioNode(this._playbackStartTime,0))};b._setDurationFromSource=function(){this._duration=1E3*this.playbackResource.duration};b._handleCleanUp=function(){this.sourceNode&&this.playState==createjs.Sound.PLAY_SUCCEEDED&&(this.sourceNode=this._cleanUpAudioNode(this.sourceNode),this._sourceNodeNext=this._cleanUpAudioNode(this._sourceNodeNext));0!=this.gainNode.numberOfOutputs&&this.gainNode.disconnect(0);clearTimeout(this._soundCompleteTimeout);this._playbackStartTime=0};b._cleanUpAudioNode=
	function(b){if(b){b.stop(0);b.disconnect(0);try{b.buffer=a._scratchBuffer}catch(c){}b=null}return b};b._handleSoundReady=function(b){this.gainNode.connect(a.destinationNode);b=.001*this._duration;var c=.001*this._position;c>b&&(c=b);this.sourceNode=this._createAndPlayAudioNode(a.context.currentTime-b,c);this._playbackStartTime=this.sourceNode.startTime-c;this._soundCompleteTimeout=setTimeout(this._endedHandler,1E3*(b-c));0!=this._loop&&(this._sourceNodeNext=this._createAndPlayAudioNode(this._playbackStartTime,
	0))};b._createAndPlayAudioNode=function(b,c){var f=a.context.createBufferSource();f.buffer=this.playbackResource;f.connect(this.panNode);var e=.001*this._duration;f.startTime=b+e;f.start(f.startTime,c+.001*this._startTime,e-c);return f};b._pause=function(){this._position=1E3*(a.context.currentTime-this._playbackStartTime);this.sourceNode=this._cleanUpAudioNode(this.sourceNode);this._sourceNodeNext=this._cleanUpAudioNode(this._sourceNodeNext);0!=this.gainNode.numberOfOutputs&&this.gainNode.disconnect(0);
	clearTimeout(this._soundCompleteTimeout)};b._resume=function(){this._handleSoundReady()};b._updateVolume=function(){var a=this._muted?0:this._volume;a!=this.gainNode.gain.value&&(this.gainNode.gain.value=a)};b._calculateCurrentPosition=function(){return 1E3*(a.context.currentTime-this._playbackStartTime)};b._updatePosition=function(){this.sourceNode=this._cleanUpAudioNode(this.sourceNode);this._sourceNodeNext=this._cleanUpAudioNode(this._sourceNodeNext);clearTimeout(this._soundCompleteTimeout);this._paused||
this._handleSoundReady()};b._handleLoop=function(){this._cleanUpAudioNode(this.sourceNode);this.sourceNode=this._sourceNodeNext;this._playbackStartTime=this.sourceNode.startTime;this._sourceNodeNext=this._createAndPlayAudioNode(this._playbackStartTime,0);this._soundCompleteTimeout=setTimeout(this._endedHandler,this._duration)};b._updateDuration=function(){this.playState==createjs.Sound.PLAY_SUCCEEDED&&(this._pause(),this._resume())};createjs.WebAudioSoundInstance=createjs.promote(c,"AbstractSoundInstance")})();
this.createjs=this.createjs||{};
(function(){function c(){this.AbstractPlugin_constructor();this._panningModel=a._panningModel;this.context=a.context;this.dynamicsCompressorNode=this.context.createDynamicsCompressor();this.dynamicsCompressorNode.connect(this.context.destination);this.gainNode=this.context.createGain();this.gainNode.connect(this.dynamicsCompressorNode);createjs.WebAudioSoundInstance.destinationNode=this.gainNode;this._capabilities=a._capabilities;this._loaderClass=createjs.WebAudioLoader;this._soundInstanceClass=
	createjs.WebAudioSoundInstance;this._addPropsToClasses()}var b=createjs.extend(c,createjs.AbstractPlugin),a=c;a._capabilities=null;a._panningModel="equalpower";a.context=null;a._scratchBuffer=null;a._unlocked=!1;a.isSupported=function(){var b=createjs.BrowserDetect.isIOS||createjs.BrowserDetect.isAndroid||createjs.BrowserDetect.isBlackberry;if("file:"==location.protocol&&!b&&!this._isFileXHRSupported())return!1;a._generateCapabilities();return null==a.context?!1:!0};a.playEmptySound=function(){if(null!=
	a.context){var b=a.context.createBufferSource();b.buffer=a._scratchBuffer;b.connect(a.context.destination);b.start(0,0,0)}};a._isFileXHRSupported=function(){var a=!0,b=new XMLHttpRequest;try{b.open("GET","WebAudioPluginTest.fail",!1)}catch(c){return a=!1}b.onerror=function(){a=!1};b.onload=function(){a=404==this.status||200==this.status||0==this.status&&""!=this.response};try{b.send()}catch(c){a=!1}return a};a._generateCapabilities=function(){if(null==a._capabilities){var b=document.createElement("audio");
	if(null==b.canPlayType)return null;if(null==a.context)if(window.AudioContext)a.context=new AudioContext;else if(window.webkitAudioContext)a.context=new webkitAudioContext;else return null;null==a._scratchBuffer&&(a._scratchBuffer=a.context.createBuffer(1,1,22050));a._compatibilitySetUp();"ontouchstart"in window&&"running"!=a.context.state&&(a._unlock(),document.addEventListener("mousedown",a._unlock,!0),document.addEventListener("touchend",a._unlock,!0));a._capabilities={panning:!0,volume:!0,tracks:-1};
	for(var c=createjs.Sound.SUPPORTED_EXTENSIONS,f=createjs.Sound.EXTENSION_MAP,e=0,g=c.length;e<g;e++){var k=c[e],l=f[k]||k;a._capabilities[k]="no"!=b.canPlayType("audio/"+k)&&""!=b.canPlayType("audio/"+k)||"no"!=b.canPlayType("audio/"+l)&&""!=b.canPlayType("audio/"+l)}2>a.context.destination.numberOfChannels&&(a._capabilities.panning=!1)}};a._compatibilitySetUp=function(){a._panningModel="equalpower";if(!a.context.createGain){a.context.createGain=a.context.createGainNode;var b=a.context.createBufferSource();
	b.__proto__.start=b.__proto__.noteGrainOn;b.__proto__.stop=b.__proto__.noteOff;a._panningModel=0}};a._unlock=function(){a._unlocked||(a.playEmptySound(),"running"==a.context.state&&(document.removeEventListener("mousedown",a._unlock,!0),document.removeEventListener("touchend",a._unlock,!0),a._unlocked=!0))};b.toString=function(){return"[WebAudioPlugin]"};b._addPropsToClasses=function(){var b=this._soundInstanceClass;b.context=this.context;b._scratchBuffer=a._scratchBuffer;b.destinationNode=this.gainNode;
	b._panningModel=this._panningModel;this._loaderClass.context=this.context};b._updateVolume=function(){var a=createjs.Sound._masterMute?0:this._volume;a!=this.gainNode.gain.value&&(this.gainNode.gain.value=a)};createjs.WebAudioPlugin=createjs.promote(c,"AbstractPlugin")})();this.createjs=this.createjs||{};
(function(){function c(){throw"HTMLAudioTagPool cannot be instantiated";}function b(a){this._tags=[]}c._tags={};c._tagPool=new b;c._tagUsed={};c.get=function(a){var b=c._tags[a];null==b?(b=c._tags[a]=c._tagPool.get(),b.src=a):c._tagUsed[a]?(b=c._tagPool.get(),b.src=a):c._tagUsed[a]=!0;return b};c.set=function(a,b){b==c._tags[a]?c._tagUsed[a]=!1:c._tagPool.set(b)};c.remove=function(a){var b=c._tags[a];if(null==b)return!1;c._tagPool.set(b);delete c._tags[a];delete c._tagUsed[a];return!0};c.getDuration=
	function(a){a=c._tags[a];return null!=a&&a.duration?1E3*a.duration:0};createjs.HTMLAudioTagPool=c;var a=b.prototype;a.constructor=b;a.get=function(){var a;a=0==this._tags.length?this._createTag():this._tags.pop();null==a.parentNode&&document.body.appendChild(a);return a};a.set=function(a){-1==createjs.indexOf(this._tags,a)&&(this._tags.src=null,this._tags.push(a))};a.toString=function(){return"[TagPool]"};a._createTag=function(){var a=document.createElement("audio");a.autoplay=!1;a.preload="none";
	return a}})();this.createjs=this.createjs||{};
(function(){function c(a,b,c,f){this.AbstractSoundInstance_constructor(a,b,c,f);this._delayTimeoutId=this._audioSpriteStopTime=null;this._endedHandler=createjs.proxy(this._handleSoundComplete,this);this._readyHandler=createjs.proxy(this._handleTagReady,this);this._stalledHandler=createjs.proxy(this._playFailed,this);this._audioSpriteEndHandler=createjs.proxy(this._handleAudioSpriteLoop,this);this._loopHandler=createjs.proxy(this._handleSoundComplete,this);c?this._audioSpriteStopTime=.001*(b+c):this._duration=
	createjs.HTMLAudioTagPool.getDuration(this.src)}var b=createjs.extend(c,createjs.AbstractSoundInstance);b.setMasterVolume=function(a){this._updateVolume()};b.setMasterMute=function(a){this._updateVolume()};b.toString=function(){return"[HTMLAudioSoundInstance]"};b._removeLooping=function(){null!=this._playbackResource&&(this._playbackResource.loop=!1,this._playbackResource.removeEventListener(createjs.HTMLAudioPlugin._AUDIO_SEEKED,this._loopHandler,!1))};b._addLooping=function(){null==this._playbackResource||
this._audioSpriteStopTime||(this._playbackResource.addEventListener(createjs.HTMLAudioPlugin._AUDIO_SEEKED,this._loopHandler,!1),this._playbackResource.loop=!0)};b._handleCleanUp=function(){var a=this._playbackResource;if(null!=a){a.pause();a.loop=!1;a.removeEventListener(createjs.HTMLAudioPlugin._AUDIO_ENDED,this._endedHandler,!1);a.removeEventListener(createjs.HTMLAudioPlugin._AUDIO_READY,this._readyHandler,!1);a.removeEventListener(createjs.HTMLAudioPlugin._AUDIO_STALLED,this._stalledHandler,!1);
	a.removeEventListener(createjs.HTMLAudioPlugin._AUDIO_SEEKED,this._loopHandler,!1);a.removeEventListener(createjs.HTMLAudioPlugin._TIME_UPDATE,this._audioSpriteEndHandler,!1);try{a.currentTime=this._startTime}catch(b){}createjs.HTMLAudioTagPool.set(this.src,a);this._playbackResource=null}};b._beginPlaying=function(a){this._playbackResource=createjs.HTMLAudioTagPool.get(this.src);return this.AbstractSoundInstance__beginPlaying(a)};b._handleSoundReady=function(a){4!==this._playbackResource.readyState?
	(a=this._playbackResource,a.addEventListener(createjs.HTMLAudioPlugin._AUDIO_READY,this._readyHandler,!1),a.addEventListener(createjs.HTMLAudioPlugin._AUDIO_STALLED,this._stalledHandler,!1),a.preload="auto",a.load()):(this._updateVolume(),this._playbackResource.currentTime=.001*(this._startTime+this._position),this._audioSpriteStopTime?this._playbackResource.addEventListener(createjs.HTMLAudioPlugin._TIME_UPDATE,this._audioSpriteEndHandler,!1):(this._playbackResource.addEventListener(createjs.HTMLAudioPlugin._AUDIO_ENDED,
	this._endedHandler,!1),0!=this._loop&&(this._playbackResource.addEventListener(createjs.HTMLAudioPlugin._AUDIO_SEEKED,this._loopHandler,!1),this._playbackResource.loop=!0)),this._playbackResource.play())};b._handleTagReady=function(a){this._playbackResource.removeEventListener(createjs.HTMLAudioPlugin._AUDIO_READY,this._readyHandler,!1);this._playbackResource.removeEventListener(createjs.HTMLAudioPlugin._AUDIO_STALLED,this._stalledHandler,!1);this._handleSoundReady()};b._pause=function(){this._playbackResource.pause()};
	b._resume=function(){this._playbackResource.play()};b._updateVolume=function(){if(null!=this._playbackResource){var a=this._muted||createjs.Sound._masterMute?0:this._volume*createjs.Sound._masterVolume;a!=this._playbackResource.volume&&(this._playbackResource.volume=a)}};b._calculateCurrentPosition=function(){return 1E3*this._playbackResource.currentTime-this._startTime};b._updatePosition=function(){this._playbackResource.removeEventListener(createjs.HTMLAudioPlugin._AUDIO_SEEKED,this._loopHandler,
		!1);this._playbackResource.addEventListener(createjs.HTMLAudioPlugin._AUDIO_SEEKED,this._handleSetPositionSeek,!1);try{this._playbackResource.currentTime=.001*(this._position+this._startTime)}catch(a){this._handleSetPositionSeek(null)}};b._handleSetPositionSeek=function(a){null!=this._playbackResource&&(this._playbackResource.removeEventListener(createjs.HTMLAudioPlugin._AUDIO_SEEKED,this._handleSetPositionSeek,!1),this._playbackResource.addEventListener(createjs.HTMLAudioPlugin._AUDIO_SEEKED,this._loopHandler,
		!1))};b._handleAudioSpriteLoop=function(a){this._playbackResource.currentTime<=this._audioSpriteStopTime||(this._playbackResource.pause(),0==this._loop?this._handleSoundComplete(null):(this._position=0,this._loop--,this._playbackResource.currentTime=.001*this._startTime,this._paused||this._playbackResource.play(),this._sendEvent("loop")))};b._handleLoop=function(a){0==this._loop&&(this._playbackResource.loop=!1,this._playbackResource.removeEventListener(createjs.HTMLAudioPlugin._AUDIO_SEEKED,this._loopHandler,
		!1))};b._updateStartTime=function(){this._audioSpriteStopTime=.001*(this._startTime+this._duration);this.playState==createjs.Sound.PLAY_SUCCEEDED&&(this._playbackResource.removeEventListener(createjs.HTMLAudioPlugin._AUDIO_ENDED,this._endedHandler,!1),this._playbackResource.addEventListener(createjs.HTMLAudioPlugin._TIME_UPDATE,this._audioSpriteEndHandler,!1))};b._updateDuration=function(){this._audioSpriteStopTime=.001*(this._startTime+this._duration);this.playState==createjs.Sound.PLAY_SUCCEEDED&&
	(this._playbackResource.removeEventListener(createjs.HTMLAudioPlugin._AUDIO_ENDED,this._endedHandler,!1),this._playbackResource.addEventListener(createjs.HTMLAudioPlugin._TIME_UPDATE,this._audioSpriteEndHandler,!1))};b._setDurationFromSource=function(){this._duration=createjs.HTMLAudioTagPool.getDuration(this.src);this._playbackResource=null};createjs.HTMLAudioSoundInstance=createjs.promote(c,"AbstractSoundInstance")})();this.createjs=this.createjs||{};
(function(){function c(){this.AbstractPlugin_constructor();this.defaultNumChannels=2;this._capabilities=a._capabilities;this._loaderClass=createjs.SoundLoader;this._soundInstanceClass=createjs.HTMLAudioSoundInstance}var b=createjs.extend(c,createjs.AbstractPlugin),a=c;a.MAX_INSTANCES=30;a._AUDIO_READY="canplaythrough";a._AUDIO_ENDED="ended";a._AUDIO_SEEKED="seeked";a._AUDIO_STALLED="stalled";a._TIME_UPDATE="timeupdate";a._capabilities=null;a.isSupported=function(){a._generateCapabilities();return null!=
	a._capabilities};a._generateCapabilities=function(){if(null==a._capabilities){var b=document.createElement("audio");if(null==b.canPlayType)return null;a._capabilities={panning:!1,volume:!0,tracks:-1};for(var c=createjs.Sound.SUPPORTED_EXTENSIONS,f=createjs.Sound.EXTENSION_MAP,e=0,g=c.length;e<g;e++){var k=c[e],l=f[k]||k;a._capabilities[k]="no"!=b.canPlayType("audio/"+k)&&""!=b.canPlayType("audio/"+k)||"no"!=b.canPlayType("audio/"+l)&&""!=b.canPlayType("audio/"+l)}}};b.register=function(a){var b=createjs.HTMLAudioTagPool.get(a.src);
	a=this.AbstractPlugin_register(a);a.setTag(b);return a};b.removeSound=function(a){this.AbstractPlugin_removeSound(a);createjs.HTMLAudioTagPool.remove(a)};b.create=function(a,b,c){a=this.AbstractPlugin_create(a,b,c);a.setPlaybackResource(null);return a};b.toString=function(){return"[HTMLAudioPlugin]"};b.setVolume=b.getVolume=b.setMute=null;createjs.HTMLAudioPlugin=createjs.promote(c,"AbstractPlugin")})();